# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# Reference doc: https://circleci.com/docs/2.0/project-walkthrough/
version: 2.1
jobs:
  build_jvm:
    docker:
      - image: circleci/openjdk:8u242-jdk
    steps:
      - checkout
      - run: cd jvm && mvn clean install
  build_python:
    docker:
      - image: circleci/python:3.7.7
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          key: deps-{{ checksum "python/requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            cd python && pip install -r requirements.txt
      - save_cache:
          key: deps-{{ checksum "python/requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            cd python && python3 -m pytest --html=pytest_report.html
      - store_artifacts:
          path: python/pytest_report.html
      - store_test_results:
          path: python/pytest_report.html

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_jvm
      - build_python

